steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA', '.']

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA']

  # Step 3: Deploy using the Cloud Run service YAML
  # This replaces the service's configuration with your local YAML file
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
      - 'run'
      - 'jobs'
      - 'deploy'
      - 'ms-dividends-etl-job' # Your Job name
      - '--image=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA'
      - '--region=$_REGION'
      - '--source=.'
      - '--set-env-vars=PROJECT_ID=$PROJECT_ID,GOOGLE_CLOUD_PROJECT=$PROJECT_ID'

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA'

substitutions:
  _REGION: us-central1
  _REPO_NAME: financial-data-etl-project
  _IMAGE_NAME: ms-etl

options:
  logging: CLOUD_LOGGING_ONLY
  machine_type: E2_HIGHCPU_8
