steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Cloud Function'
    entrypoint: bash
    env:
      - GOOGLE_CLOUD_PROJECT=$_PROJECT
      - ENVIRONMENT=$_ENV
      - BUCKET_SUFFIX=$_BUCKET_SUFFIX
    args:
      - -c
      - |
        # DEBUG: print substitutions at runtime
        echo "==============================="
        echo "==== Debug Build Variables ===="
        echo "_PROJECT=$_PROJECT"
        echo "GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT"
        echo "ENVIRONMENT=$ENVIRONMENT"
        echo "BUCKET_SUFFIX=$BUCKET_SUFFIX"

        # Deploy the Cloud Function
        echo "**** Deploying Cloud Function ****"
        gcloud functions deploy market-stack-dividends-extract \
          --gen2 \
          --runtime=python310 \
          --region=us-central1 \
          --project=$$GOOGLE_CLOUD_PROJECT \
          --service-account=market-stack-func-gcs-uploader@$$GOOGLE_CLOUD_PROJECT.iam.gserviceaccount.com \
          --entry-point=extract_dividends \
          --source=dividends \
          --allow-unauthenticated \
          --trigger-http \
          --min-instances=0 \
          --max-instances=1 \
          --timeout=480s \
          --set-env-vars ENVIRONMENT=$$ENVIRONMENT,BUCKET_SUFFIX=$$BUCKET_SUFFIX,GOOGLE_CLOUD_PROJECT=$$GOOGLE_CLOUD_PROJECT

        if [ $? -eq 0 ]; then
          echo "✅ Cloud Function deployed successfully."
        else
          echo "❌ Deployment failed."
          exit 1
        fi

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Upload PySpark Job'
    entrypoint: bash
    args:
      - -c
      - |
        echo "**** Copying transfer.py to GCS bucket... ****"
        gsutil cp dividends/src/transform/transformer.py gs://market-stack-code-dev/dataproc/dividends/transform/transformer.py;
        
        if [ $? -eq 0 ]; then
          echo "File copied successfully."
        else
          echo "Failed to copy file."
          exit 1
        fi

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: 'ALLOW_LOOSE'