steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - market-stack-dividends-json-extract
      - --gen2
      - --runtime=python310
      - --region=us-central1
      - --trigger-http
      - --service-account=market-stack-func-gcs-uploader@project-e6aecb7b-2aa0-4815-8c3.iam.gserviceaccount.com
      - --entry-point=extract_dividends_entry_point
      - --source=dividends
      - --allow-unauthenticated
      - --no-gen2

options:
  logging: CLOUD_LOGGING_ONLY