steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Cloud Function'
    entrypoint: bash
    env:
      - GOOGLE_CLOUD_PROJECT=$PROJECT_ID
      - ENVIRONMENT=$_ENV
    args:
      - -c
      - |
        set -e  # exit immediately if a command exits with a non-zero status, and prevents partial deployment
        
        # Deploy the Cloud Function
        echo "**** Deploying Cloud Function ****"
        # DEBUG: print substitutions at runtime
        echo ===================================================
        echo =========+==== Debug Build Variables ==============
        echo "GOOGLE_CLOUD_PROJECT=$$GOOGLE_CLOUD_PROJECT"
        echo "ENVIRONMENT=$$ENVIRONMENT"
        echo ===================================================

        # Prepare the Cloud Function source code directory
        rm  -rf  ms_div_extract_cf
        mkdir  -p  ms_div_extract_cf

        # Copy Cloud Function entrypoint
        cp  dividends/extract/jobs/main.py  ms_div_extract_cf/

        # Copy requirements file
        cp  dividends/extract/jobs/requirements.txt  ms_div_extract_cf/

        # Copy extraction logic
        mkdir  -p  ms_div_extract_cf/src
        cp  -r dividends/extract/src/.  ms_div_extract_cf/src/
        
        # Copy shared files
        mkdir  -p  ms_div_extract_cf/shared
        cp  -r  dividends/shared/.  ms_div_extract_cf/shared/

        gcloud functions deploy market-stack-dividends-extract \
          --gen2 \
          --runtime=python310 \
          --region=us-central1 \
          --project=$$GOOGLE_CLOUD_PROJECT \
          --service-account=market-stack-func-gcs-uploader@$$GOOGLE_CLOUD_PROJECT.iam.gserviceaccount.com \
          --entry-point=extract_dividends \
          --source=ms_div_extract_cf \
          --allow-unauthenticated \
          --trigger-http \
          --min-instances=0 \
          --max-instances=1 \
          --timeout=480s \
          --set-env-vars ENVIRONMENT=$$ENVIRONMENT,GOOGLE_CLOUD_PROJECT=$$GOOGLE_CLOUD_PROJECT

        if [ $? -eq 0 ]; then
          echo "✅ Cloud Function deployed successfully."
        else
          echo "❌ Deployment failed."
          exit 1
        fi

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Upload PySpark Job'
    entrypoint: bash
    args:
      - -c
      - |
        echo "**** Copying transfer.py to GCS bucket... ****"
        #### NEED TO CHANGE TRANSFORM MAIN FILE SO THAT ITS SEPARATE FROM EXTRACT MAIN FILE, THEN UPDATE THIS STEP TO COPY TRANSFORM MAIN FILE INSTEAD OF EXTRACT MAIN FILE
        gsutil cp dividends/transform/src/transformer.py gs://market-stack-code-dev/dataproc/dividends/transform/src/transformer.py;
        gsutil cp dividends/transform/jobs/transform_job.py gs://market-stack-code-dev/dataproc/dividends/transform/jobs/transform_job.py;

        if [ $? -eq 0 ]; then
          echo "File copied successfully."
        else
          echo "Failed to copy file."
          exit 1
        fi

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: 'ALLOW_LOOSE'