steps:

# 0️⃣ Pull previous image for cache (ignore error if first build)
- id: pull-cache
  name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
    - -c
    - |
      docker pull $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:latest || exit 0
  waitFor: ['-']

# 1️⃣ Build image using cache
- id: build
  name: gcr.io/cloud-builders/docker
  args:
    [
      "build",
      "-t",
      "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA",
      "-t",
      "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:latest",
      "--cache-from",
      "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:latest",
      "."
    ]
  waitFor: ['pull-cache']

# 2️⃣ Prepare YAML in-place
- id: prepare-yaml
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - -c
    - |
      sed -i "s|ENVIRONMENT_PLACEHOLDER|$_ENV|g" cloudrun.yaml
      sed -i "s|PROJECT_ID_PLACEHOLDER|$PROJECT_ID|g" cloudrun.yaml
      sed -i "s|IMAGE_PLACEHOLDER|$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA|g" cloudrun.yaml
  waitFor: ['-']

# 3️⃣ Push image
- id: push
  name: gcr.io/cloud-builders/docker
  args:
    [
      "push",
      "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA"
    ]
  waitFor: ['build']

# 3b️⃣ Push latest tag (needed for caching)
- id: push-latest
  name: gcr.io/cloud-builders/docker
  args:
    [
      "push",
      "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:latest"
    ]
  waitFor: ['build']

# 4️⃣ Deploy Cloud Run Job
- id: deploy-job
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  args:
    [
      "gcloud",
      "run",
      "jobs",
      "replace",
      "cloudrun.yaml",
      "--region=$_REGION"
    ]
  waitFor: ['push', 'push-latest', 'prepare-yaml']

# 5️⃣ Execute Job
- id: run-job
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  args:
    [
      "gcloud",
      "run",
      "jobs",
      "execute",
      "ms-cloudrun-etl-job",
      "--region=$_REGION"
    ]
  waitFor: ['deploy-job']

images:
- "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA"
- "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:latest"

options:
  logging: CLOUD_LOGGING_ONLY
  #machineType: E2_HIGHCPU_8

# Within the trigger settings already
#substitutions:
#  _REPO_NAME: financial-data-etl-project
#  _IMAGE_NAME: ms-etl
#  _REGION: us-central1
#  _ENV: dev