steps:
  - name: 'alpine'
    entrypoint: sh
    args:
      - -c
      - |
        echo "Listing contents of dividends folder:"
        ls -la dividends

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - market-stack-dividends-json-extract
      - --runtime=python310
      - --region=us-central1
      - --trigger-http
      - --entry-point=main
      - --source=dividends
      - --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY