apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: ms-cloudrun-etl-job
spec:
  template:
    spec:
      template:
        spec:
          serviceAccountName: ms-cloudrun-etl-sa
          containers:
            - name: ms-etl-container
              image: us-central1-docker.pkg.dev/your-gcp-project-id/financial-data-etl-project/ms-etl:a363ef16
              command: ["python"]
              args: ["dividends/run_etl.py"]
              env:
                - name: PROJECT_ID
                  value: your-gcp-project-id
                - name: ENVIRONMENT
                  value: dev
              resources:
                limits:
                  cpu: "2"
                  memory: "512Mi"
          timeoutSeconds: 1800
          maxRetries: 1