steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - market-stack-dividends-json-extract
      - --runtime=python310
      - --region=us-central1
      - --trigger-http
      - --entry-point=extract_dividends_main
      - --source=dividends
      - --allow-unauthenticated
      - --no-gen2

options:
  logging: CLOUD_LOGGING_ONLY