steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Upload PySpark Job'
    entrypoint: bash
    args:
      - -c
      - |
        echo "**** Copying transfer.py to GCS bucket... ****"
        if gsutil cp dividends/code/transform.py gs://market-stack-code-dev/dataproc/dividends/transform.py;
        then
          echo "File copied successfully."
        else
          echo "Failed to copy file."
          exit 1
        fi

options:
  logging: CLOUD_LOGGING_ONLY